import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WrapComponent from "./components/wrapComponent";
import NavBar from "./components/NavBar";
import {NavItem} from "./components/NavBar";
import Footre from "./components/Footre";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <WrapComponent  >
       <NavBar>
            <NavItem item="Home"/>
            <NavItem item="services"/>
            <NavItem item="doctors"/>
            <NavItem item="about us "/>
            <NavItem item="contact"/>
       </NavBar>
           {children}
         <Footre />  
       </WrapComponent>
      </body>
    </html>
  );
}


